### ISSUE TITLE
Reason for the negative notation for the perplexity score

### ISSUE THREAD

**Issue by snoop2head** [ftramer/LM_Memorization#2]
https://github.com/ftramer/LM_Memorization/blob/997ff99a18018989a1643a568e966ba890bef4c1/extraction.py#L171

<img width="598" alt="Screen Shot 2022-07-28 at 6 41 10 PM" src="https://user-images.githubusercontent.com/28736695/181474901-8f76f3c3-2e93-442a-9211-4490dee61a62.png">

May I know why there is minus notation in front of the perplexity score? I believe the paper states that perplexity metric is the exponential of the loss is the perplexity metric. Or is negative notation for the sorting purpose?

**Comment by ftramer** [comment]
Yeah that's just there for sorting purposes
