### ISSUE TITLE
CC slice download link is not available

### ISSUE THREAD

**Issue by everks** [ftramer/LM_Memorization#3]
download.sh shows 403

**Comment by ftramer** [comment]
Looks like the URL to download it changed. While I figure out where it went, you can get it from here in the meanwhile:
https://archive.org/download/CC-MAIN-2021-21-1620243988696.23-0000/CC-MAIN-20210505203909-20210505233909-00000.warc.gz

**Comment by ftramer** [comment]
Sorry disregard the above comment. That's not the WET file.
The issue was fixed in baafa17
